name: Laden
favicon: null
layout_spectrum: 0.82713
typography_spectrum: 0.97011
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101010'
    - '#b79b86'
    - '#ffffff'
    - '#e74014'
    - '#369408'
  brandStrength: 0.125
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
